spring:
  data:
    mongodb:
      username: gusain
      password: gusain
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.gusain.ecommerce.kafka.OrderConfirmation,paymentConfirmation:com.gusain.payment.notification.PaymentNotificationRequest
      group-id: paymentGround, orderGroup
      auto-offset-reset: earliest
  application:
    name: notification-service
  mail:
    host: localhost
    port: 1025
    username: gusain
    password: gusain
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8040
