spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: product-service


#flyway is a database migration tool that helps you manage
#and version control your database schema changes across environments
#Think of it like GIT for your database-
#IT keeps tract of all the changes you make to your datbase
#structure over time.